# Generated by Django 5.1.6 on 2025-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_roomimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dorm',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('dorm', 'room_number', 'slug')},
        ),
    ]
