# Generated by Django 5.1.7 on 2025-04-30 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_alter_room_unique_together_dorm_slug_room_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dorm",
            name="labels",
            field=models.CharField(
                max_length=255, blank=True, null=True
            ),  # Use CharField instead of ArrayField
        ),
    ]
