# Generated by Django 5.1.6 on 2025-03-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_post_image_postimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails'),
        ),
    ]
