# Generated by Django 5.1.7 on 2025-04-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_dorm_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dorm",
            name="labels",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
