# Generated by Django 5.1.6 on 2025-03-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_postimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
